### ISSUE TITLE
exclude_from_nav

### ISSUE THREAD

**Issue by cekk** [RedTurtle/design.plone.ioprenoto#6]
https://github.com/RedTurtle/design.plone.ioprenoto/blob/8e033dabba7ebf39b6b9978434cac5b444e84cf4/src/design/plone/ioprenoto/content/PrenotazioniFolder.py#L8

Non credo sia il modo corretto di farlo..se per caso qualcuno volesse abilitare una FolderPrenotazioni alla navigazione, con la tua modifica ce la farebbe?

Visto che è un campo/attributo dell'oggetto, non è meglio usare un eventhandler alla creazione?

**Comment by foxtrot-dfm1** [comment]
> https://github.com/RedTurtle/design.plone.ioprenoto/blob/8e033dabba7ebf39b6b9978434cac5b444e84cf4/src/design/plone/ioprenoto/content/PrenotazioniFolder.py#L8
> 
> Non credo sia il modo corretto di farlo..se per caso qualcuno volesse abilitare una FolderPrenotazioni alla navigazione, con la tua modifica ce la farebbe?
> 
> Visto che è un campo/attributo dell'oggetto, non è meglio usare un eventhandler alla creazione?

@cekk https://github.com/RedTurtle/redturtle.prenotazioni/search?q=exclude_from_nav

**Comment by cekk** [comment]
A posto..non me lo ricordavo. Lasciamo così allora
